name: mypage
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  division: ^0.9.0
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  get: 4.3.7
  google_fonts: 2.1.0
  octo_image: ^1.0.0+1
  url_strategy: 0.2.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
